### PR TITLE
placed calendar outside the tab

### PR DESCRIPTION
**Pull request by screenflow6**
Edited talks.html and style.css.
Placed calendar outside the tab as requested.

### CODE REVIEW

**Comment by rjurney** [comment]
Hey, your pull request removes all the updates I made to talks.html :( I will have to figure out what to do about this tomorrow.

**Comment by screenflow6** [comment]
I have just copied your full code, edited it in my editor and pasted here again. I dint alter anything else.

**Comment by screenflow6** [comment]
Added six new talks to the list

**Comment by rjurney** [comment]
Thank you so much!

**Pull request merged**
